blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('blog/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('blog-comments/<int:blog_id>/', views.add_comment, name='add_comment'),
]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add-to-cart'),
    path('cart-status/', views.cart_status, name='cart-status'),
    path('remove-item/', views.remove_item, name='remove-item'),
    path('detail/', views.cart_detail, name='cart-detail'),
    path('update-cart/', views.update_quantity, name='update-quantity'),
    path('order/<int:order_id>/', views.order, name='order'),
    path('request/', views.add_address, name='add-address'),
    path('verify/', views.verify, name='verify'),
]

nightShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
app_name = 'store'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('products-by-category/<int:category_id>/<slug:slug>/', views.product_by_category, name='product_by_category'),
    path('product-detail/<int:product_id>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('add-to-favorite/<int:id>/', views.add_to_favorite, name='add_to-favorite'),
    path('list-favorites/', views.list_favorite, name='list_favorite'),
    path('remove-favorite/<int:id>/', views.remove_favorite, name='remove_favorite'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('add-email/', views.emails, name='add_email'),
    path('discount-code/', views.apply_copen, name='discount_code'),
]

cart/models.py
from django.db import models
from account.models import NightUser
from store.models import Product


# Create your models here.

class Address(models.Model):
    user = models.ForeignKey(NightUser, on_delete=models.CASCADE, related_name='address')
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    province = models.CharField(max_length=25)
    city = models.CharField(max_length=25)
    detailed_address = models.TextField()
    postal_code = models.CharField(max_length=11, validators=[])
    plaque = models.CharField(max_length=10)
    recipient_phone = models.CharField(max_length=11)
    note = models.CharField(max_length=125, blank=True, null=True)

    def __str__(self):
        return f'{self.user.email} -> {self.detailed_address}'


# Orders


class Order(models.Model):
    class Status(models.TextChoices):
        ORDER_CONFIRMATION = 'تایید سفارش', "تایید سفارش"
        review_queue = 'در صف بررسی', "در صف بررسی"
        preparation = 'آماده‌سازی', "آماده‌سازی"
        Delivery_to_post = 'تحویل به پست', "تحویل به پست"

    buyer = models.ForeignKey(NightUser, on_delete=models.SET_NULL, null=True, related_name='orders')
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, related_name='address')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    status = models.CharField(choices=Status.choices, max_length=20, default=Status.ORDER_CONFIRMATION)

    class Meta:
        ordering = ['-updated']
        indexes = [
            models.Index(fields=['-updated'])
        ]

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum([item.get_cost() for item in self.items.all()])

    def get_post_cost(self):
        weight = sum([item.get_weight() for item in self.items.all()])
        if weight < 1000:
            return 50000
        else:
            return 150000

    def get_final_cost(self):
        return self.get_total_cost() + self.get_post_cost()


class OrderItem(models.Model):
    orders = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name='order_items')
    price = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=1)
    weight = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.product.name} * {self.quantity}'

    def get_cost(self):
        return self.quantity * self.price

    def get_weight(self):
        return self.quantity * self.weight

cart/forms.py
from django import forms
from .models import Address


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            'first_name', 'last_name',
            'province', 'city', 'detailed_address',
            'postal_code', 'plaque', 'recipient_phone',
            'note'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['province'].required = True
        self.fields['city'].required = True
        self.fields['detailed_address'].required = True
        self.fields['postal_code'].required = True
        self.fields['plaque'].required = True
        self.fields['recipient_phone'].required = True
        self.fields['note'].required = False

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .cart import Cart
from store.models import Product
from .forms import InvoiceForm
from .models import Order, OrderItem

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import requests
import logging


# Create your views here.

@require_POST
def add_to_cart(request, product_id):
    try:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        result = cart.add(product)

        if not result['success']:
            return JsonResponse({'error': result['message']}, status=400)

        return JsonResponse({
            'success': True,
            'item_count': len(cart),
            'total_price': cart.get_total_price(),
            'message': result['message']
        })

    except Product.DoesNotExist:
        return JsonResponse({'error': 'محصول یافت نشد.'}, status=404)
    except Exception as e:
        return JsonResponse({'error': f'خطا: {str(e)}'}, status=400)


def cart_status(request):
    cart = Cart(request)

    response = {
        'item_count': len(cart),
        'total_price': cart.get_total_price(),
    }

    return JsonResponse(response)


def remove_item(request):
    if request.method == 'POST':
        product_id = request.POST.get('item_id')
        cart = Cart(request)
        try:
            if product_id:
                product = get_object_or_404(Product, id=product_id)
                cart.remove(product)
                return JsonResponse({'success': True, 'total_price': cart.get_total_price(), 'item_count': len(cart)})
        except Exception as e:
            return JsonResponse({'error': str(e)})
    return JsonResponse({'error': 'Invalid request method'})


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart.html', {'cart': cart})


def update_quantity(request):
    try:
        item_id = request.POST.get('item_id')
        action = request.POST.get('action')

        if not item_id or not action:
            return JsonResponse({'success': False, 'error': 'Invalid input.'}, status=400)

        cart = Cart(request)
        product = get_object_or_404(Product, id=item_id)

        if action == 'decrease':
            cart.decrease(product)
        elif action == 'add':
            cart.add(product)
        else:
            return JsonResponse({'success': False, 'error': 'Invalid action.'}, status=400)

        context = {
            'total_price': cart.get_total_price(),
            'quantity': cart.cart[str(product.id)]['quantity'],
            'success': True,
        }
        return JsonResponse(context)

    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)}, status=500)


logger = logging.getLogger(__name__)


def add_address(request):
    if request.method == "POST":
        form = InvoiceForm(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.save()

            cart = Cart(request)

            description = ''
            for item in cart:
                description += str(item['product'].name) + ', '

            data = {
                "merchant_id": settings.MERCHANT,
                "amount": cart.get_final_price(),
                "callback_url": settings.ZARINPAL_CALLBACK_URL,
                "description": description,
            }
            headers = {"Content-Type": "application/json"}

            try:
                response = requests.post(settings.ZARINPAL_REQUEST_URL, json=data, headers=headers)
                response_data = response.json()
                print(response_data)  # چاپ پاسخ برای بررسی جزئیات

                if response_data.get('data') and response_data['data']['code'] == 100:
                    return redirect(f"https://sandbox.zarinpal.com/pg/StartPay/{response_data['data']['authority']}")
                else:
                    return JsonResponse({'success': False, 'message': f"خطا در درخواست پرداخت: {response_data.get('errors', 'جزئیات خطا موجود نیست')}"})
            except Exception as e:
                return JsonResponse({'success': False, 'message': f"خطا در ارسال درخواست: {e}"})

    else:
        form = InvoiceForm()

    return render(request, 'cart/invoice.html', {'form': form})


@login_required
def order(request, order_id):
    orders = get_object_or_404(Order, pk=order_id, buyer=request.user, paid=True)
    return render(request, 'cart/order.html', {'orders': orders})


@csrf_exempt
def verify(request):
    print(40 * '_____')
    authority = request.GET.get('Authority')
    status = request.GET.get('Status')

    if not authority or not status:
        return HttpResponse("درخواست نامعتبر است.")

    if status == 'OK':
        cart = Cart(request)
        data = {
            "merchant_id": settings.MERCHANT,
            "amount": cart.get_final_price(),  # مطمئن شوید مبلغ درست استفاده می‌شود
            "authority": authority,
        }
        headers = {"Content-Type": "application/json"}

        try:
            response = requests.post(settings.ZARINPAL_VERIFY_URL, json=data, headers=headers)
            response_data = response.json()

            if response_data.get('data') and response_data['data']['code'] == 100:
                order = Order.objects.create(
                    buyer=request.user,
                    address=request.user.addresses.last(),
                    paid=True
                )

                for item in cart:
                    OrderItem.objects.create(
                        orders=order,
                        product=item['product'],
                        price=item['price'],
                        quantity=item['quantity'],
                        weight=item['weight']
                    )

                    product = item['product']
                    quantity = item['quantity']

                    if product.inventory > quantity:
                        product.inventory -= quantity
                        product.sell += quantity
                        product.save()
                    else:
                        return render(request, 'cart/order.html', {'success': False, 'message': 'موجودی ناکافی'})

                cart.clear()  # پاک کردن سبد خرید
                return render(request, 'cart/order.html', {'success': True, 'message': f"پرداخت موفق! شماره تراکنش: {response_data['data']['ref_id']}", 'orders': order})
            else:
                return render(request, 'cart/order.html', {'success': False, 'message': 'خطا در تایید پرداخت'})
        except Exception as e:
            return render(request, 'cart/order.html', {'success': False, 'message': "خطا در تایید پرداخت"})
    else:
        return render(request, 'cart/order.html', {'success': False, 'message': "پرداخت توسط کاربر لغو شد."})

cart/templates/cart/cart.html
{% extends 'parent/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/god.css' %}">{% endblock %}
       {% block content %}
        <main class="main cart rtl text-right">
            <div class="page-content pt-7 pb-10">
                <div class="step-by pr-4 pl-4">
                    <h3 class="title title-simple title-step active"><a href="cart.html" class="disabled">1. سبد خرید</a></h3>
                    <h3 class="title title-simple title-step"><a href="checkout.html" class="disabled">2. صورت حساب</a></h3>
                    <h3 class="title title-simple title-step"><a href="order.html" class="disabled">3. تکمیل خرید</a></h3>
                </div>
                <div class="container mt-7 mb-2">
                    <div class="row">
                        <div class="col-lg-8 col-md-12 pr-lg-4">
                            <table class="shop-table cart-table">
                                <thead>
                                    <tr>
                                        <th><span>محصول</span></th>
                                        <th></th>
                                        <th><span>قیمت</span></th>
                                        <th><span>تعداد</span></th>
                                        <th>قیمت بعد از تخفیف</th>
                                    </tr>
                                </thead>
                                    <tbody class="reload-cart">
                                        {% for item in cart %}
                                            <tr>
                                                <td class="product-thumbnail">
                                                    <figure>
                                                        <a href="{{ item.product.get_absolute_url }}">
                                                            <img src="{{ item.product.images.first.file.url }}" width="100" height="100" alt="product">
                                                        </a>
                                                    </figure>
                                                </td>
                                                <td class="product-name">
                                                    <div class="product-name-section">
                                                        <a href="{{ item.product.get_absolute_url }}">{{ item.product.name }}</a>
                                                    </div>
                                                </td>
                                                <td class="product-subtotal">
                                                    <span class="amount">{{ item.price }} تومان</span>
                                                </td>
                                                <td class="product-quantity">
                                                    <div class="input-group" data-product-id="{{ item.product.id }}">
                                                        <button class="quantity-minus d-icon-minus"></button>
                                                        <input class="form-control my-quantity" type="number" value="{{ item.quantity }}" disabled>
                                                        <button class="quantity-plus d-icon-plus"></button>
                                                    </div>
                                                </td>

                                                <td class="product-price">
                                                    <span class="amount">{{ item.product.new_price }} تومان</span>
                                                </td>
                                                <td class="product-close">
                                                    <a href="#" class="product-remove" title="حذف محصول" data-product-id="{{ item.product.id }}">
                                                        <i class="fas fa-times"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            {% empty %}
                                            <tr>
                                                <td colspan="6" class="text-center">سبد خرید خالی است.</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>

                            </table>
                            <div class="cart-actions mb-6 pt-4">
                                <a href="{% url 'store:index' %}" class="btn btn-dark btn-md btn-rounded btn-icon-left ml-4 mb-4">
                                    ادامه خرید<i class="d-icon-arrow-left"></i>
                                </a>
                                <button type="submit"
                                        class="btn btn-outline btn-dark btn-md btn-rounded btn-disabled">
                                    به روز رسانی سبد خرید

                                </button>
                            </div>
                        </div>
                        <aside class="col-lg-4 sticky-sidebar-wrapper">
                            <div class="sticky-sidebar" data-sticky-options="{'bottom': 20}">
                                <div class="summary mb-4">
                                    <h3 class="summary-title">جمع سبد خرید</h3>
                                    <table class="shipping">
                                        <tr class="summary-subtotal">
                                            <td>
                                                <h4 class="summary-subtitle">جمع بعد از تخفیف</h4>
                                            </td>
                                            <td>
                                                <p class="summary-subtotal-price">{{ cart.get_total_price }} تومان</p>
                                            </td>
                                        </tr>
                                        <tr class="sumnary-shipping shipping-row-last">

                                        </tr>
                                    </table>

                                    <table class="total">
                                        <tr class="summary-subtotal">
                                            <td>
                                                <h4 class="summary-subtitle">جمع</h4>
                                            </td>
                                            <td>
                                                <p class="summary-total-price ls-s">{{ cart.get_total_price}} تومان</p>
                                            </td>
                                        </tr>
                                    </table>
                                    <a href="{% url 'cart:add-address' %}" class="btn btn-dark btn-rounded btn-checkout {% if not cart %}disabled{% endif %}">
                                        صورت حساب
                                    </a>
                                </div>
                            </div>
                        </aside>
                    </div>
                </div>
            </div>
        </main>

           <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
           <script>
                $(document).ready(function() {
                    $('.product-remove').click(function(e) {
                        e.preventDefault();
                        var button = $(this);
                        var ProductId = button.data('product-id');
                        $.ajax({
                            url: '{% url "cart:remove-item" %}',
                            method: 'POST',
                            data: {
                                'item_id': ProductId,
                                'csrfmiddlewaretoken': '{{ csrf_token }}'
                            },
                            success: function(data) {
                                if (data.success) {
                                    button.closest('tr').remove();
                                    $('.summary-subtotal-price').text(data.total_price + "تومان");
                                    $('.summary-total-price').text(data.total_price + "تومان");


                                    if ($('.reload-cart tr').length === 0) {
                                        $('.reload-cart').html('<tr><td colspan="6" class="text-center">سبد خرید خالی است.</td></tr>');
                                        $('.btn-checkout').addClass('disabled')
                                    }
                                } else {
                                    alert(data.message || 'خطا در حذف محصول.');
                                }
                            },
                            error: function(xhr, status, error) {
                                console.log('AJAX Error:', error);
                                alert('مشکلی در ارتباط با سرور وجود دارد.');
                            }
                        });
                    });

                    $('.quantity-minus').click(function(e) {
                        e.preventDefault();
                        var button = $(this);
                        var productId = button.closest('.input-group').data('product-id'); // شناسایی شناسه محصول

                        $.ajax({
                            url: '{% url "cart:update-quantity" %}',
                            type: 'POST',
                            data: {
                                'csrfmiddlewaretoken': '{{ csrf_token }}',
                                'action': 'decrease',
                                'item_id': productId
                            },
                            success: function(data) {
                                var quantityInput = button.closest('.input-group').find('input');
                                quantityInput.val(data.quantity);

                                $('.summary-subtotal-price').text(data.total_price+ "تومان");
                                $('.summary-total-price').text(data.total_price+ "تومان");

                                if (data.quantity === 0) {
                                    button.closest('tr').remove();

                                    if ($('.reload-cart tr').length === 0) {
                                        $('.reload-cart').html('<tr><td colspan="6" class="text-center">سبد خرید خالی است.</td></tr>');
                                        $('.btn-checkout').addClass('disabled');
                                    }
                                }
                            },
                            error: function(xhr, status, error) {
                                console.log('AJAX Error:', error);
                                alert('مشکلی در ارتباط با سرور وجود دارد.');
                            }
                        });
                    });

                    // افزایش تعداد محصول
                    $('.quantity-plus').click(function(e) {
                        e.preventDefault();
                        var button = $(this);
                        var productId = button.closest('.input-group').data('product-id');

                        $.ajax({
                            url: '{% url "cart:update-quantity" %}',
                            type: 'POST',
                            data: {
                                'csrfmiddlewaretoken': '{{ csrf_token }}',
                                'action': 'add',
                                'item_id': productId
                            },
                            success: function(data) {
                                var quantityInput = button.closest('.input-group').find('input');
                                quantityInput.val(data.quantity);

                                // بروزرسانی قیمت‌ها
                                $('.summary-subtotal-price').text(data.total_price + "تومان");
                                $('.summary-total-price').text(data.total_price + 'تومان');
                            },
                            error: function(xhr, status, error) {
                                console.log('AJAX Error:', error);
                                alert('مشکلی در ارتباط با سرور وجود دارد.');
                            }
                        });
                    });
                });
           </script>
{% endblock %}

cart/templates/cart/order.html
{% extends 'parent/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/god.css' %}" xmlns="http://www.w3.org/1999/html">{% endblock %}
{% block content %}
    		<main class="main order rtl text-right">
			<div class="page-content pt-7 pb-10 mb-10">
				<div class="step-by pr-4 pl-4">
					<h3 class="title title-simple title-step"><a href="cart.html" class="disabled">1. سبد خرید</a></h3>
					<h3 class="title title-simple title-step"><a href="checkout.html" class="disabled">2. صورت حساب</a></h3>
					<h3 class="title title-simple title-step active"><a href="order.html" class="disabled">3. تکمیل خرید</a></h3>
				</div>
				<div class="container mt-8">
					<div class="order-message mr-auto ml-auto">
						<div class="icon-box d-inline-flex align-items-center">
							<div class="icon-box-icon mb-0">
								<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
									xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 50 50"
									enable-background="new 0 0 50 50" xml:space="preserve">
									<g>
										<path fill="none" stroke-width="3" stroke-linecap="round"
											stroke-linejoin="bevel" stroke-miterlimit="10" d="
											M33.3,3.9c-2.7-1.1-5.6-1.8-8.7-1.8c-12.3,0-22.4,10-22.4,22.4c0,12.3,10,22.4,22.4,22.4c12.3,0,22.4-10,22.4-22.4
											c0-0.7,0-1.4-0.1-2.1"></path>
										<polyline fill="none" stroke-width="4" stroke-linecap="round"
											stroke-linejoin="bevel" stroke-miterlimit="10" points="
											48,6.9 24.4,29.8 17.2,22.3 	"></polyline>
									</g>
								</svg>
							</div>
                            {% if orders %}
							<div class="icon-box-content text-right">
								<h5 class="icon-box-title font-weight-bold lh-1 mb-1">متشکریم از خرید شما!</h5>
								<p class="lh-1 ls-m"> خرید شما در انتظار ارسال است  </p>
							</div>
						</div>
					</div>
					<div class="order-results">
						<div class="overview-item">
							<span>شماره سفارش:</span>
							<strong>{{ orders.id }}</strong>
						</div>
						<div class="overview-item">
							<span>وضعیت:</span>
							<strong>{{ orders.status }}</strong>
						</div>
						<div class="overview-item">
							<span> تاریخ  :</span>
							<strong>{{ orders.created }}</strong>
						</div>
						<div class="overview-item">
							<span>ایمیل:</span>
							<strong>{{ orders.buyer.email }}</strong>
						</div>
						<div class="overview-item">
							<span> جمع:</span>
							<strong> {{ orders.get_final_cost }} تومان </strong>
						</div>
						<div class="overview-item">
							<span>روش پرداخت:</span>
							<strong>درگاه پرداخت</strong>
						</div>
					</div>
					<h2 class="title title-simple text-right pt-4 font-weight-bold text-uppercase">جزئیات فاکتور</h2>
					<div class="order-details">
						<table class="order-details-table">
							<thead>
								<tr class="summary-subtotal">
									<td>
										<h3 class="summary-subtitle">محصول</h3>
									</td>
									<td></td>
								</tr>
							</thead>
							<tbody>
                            {% for item in orders.items.all %}
								<tr>
									<td class="product-name">{{ item.product.name }}<span> <i class="fas fa-times"></i>
											1</span></td>
									<td class="product-price"> {{ item.price }} تومان </td>
								</tr>
                            {% endfor %}

								<tr class="summary-subtotal">
									<td>
										<h4 class="summary-subtitle">جمع قبل از تخفیف:</h4>
									</td>
									<td class="summary-subtotal-price"> {{ orders.get_total_cost }} تومان </td>
								</tr>
								<tr class="summary-subtotal">
									<td>
										<h4 class="summary-subtitle"> حمل و نقل:</h4>
									</td>
									<td class="summary-subtotal-price">{{ orders.get_post_cost }}  </td>
								</tr>
								<tr class="summary-subtotal">
									<td>
										<h4 class="summary-subtitle">روش پرداخت:</h4>
									</td>
									<td class="summary-subtotal-price">مستقیم  درگاه پرداخت</td>
								</tr>
								<tr class="summary-subtotal">
									<td>
										<h4 class="summary-subtitle"> جمع:</h4>
									</td>
									<td>
										<p class="summary-total-price"> {{ orders.get_final_cost }} تومان </p>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<h2 class="title title-simple text-right pt-10 mb-2">آدرس مقصد</h2>
					<div class="address-info pb-8 mb-6">
						<p class="address-detail pb-2">
							<br>
                            {{ orders.address.province }}-{{ orders.address.city }}<br>
                            {{ orders.address.detailed_address}}-{{ orders.address.postal_code }}<br>
							{{ orders.address.recipient_phone }}
						</p>
						<p class="email">{{ orders.buyer.email }}</p>
					</div>
					<a href="{% url 'store:index' %}" class="btn btn-icon-right btn-dark btn-back btn-rounded btn-md mb-4">بازگشت به فروشگاه<i
							class="d-icon-arrow-left"></i></a>
				</div>
			</div>
                                {{ message }}
            {% else %}
                                <div class="icon-box-content text-right">
                                    <h5 class="icon-box-title font-weight-bold lh-1 mb-1">پرداخت انجام نشد!</h5>
                                    <p class="lh-1 ls-m"><a href="{% url 'store:index' %}">بازگشت به فروشگاه</a></p>
                                    <p class="lh-1 ls-m"><a href="{% url 'store:index' %}">{{ message }}</a></p>
                                </div>
            {% endif %}
		</main>
{% endblock %}