account/urls.py
from django.urls import path, include
from . import views
app_name = 'account'

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('verify_token/', views.verify_email, name='verify_token'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('detail/', views.detail, name='detail'),
    path('complete-information/', views.complete_detail_account, name='complete-information'),
    path('forget-password/', views.forget_password, name='forget-password'),
    path('confirm-password-change/', views.verifi_token_forget_password, name='confirm-password-change'),
    path('forget-master-password/', views.forget_master_password, name='forget-master-master'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('blog/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('blog-comments/<int:blog_id>/', views.add_comment, name='add_comment'),
]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add-to-cart'),
    path('cart-status/', views.cart_status, name='cart-status'),
    path('remove-item/', views.remove_item, name='remove-item'),
    path('detail/', views.cart_detail, name='cart-detail'),
    path('update-cart/', views.update_quantity, name='update-quantity'),
    path('order/<int:order_id>/', views.order, name='order'),
    path('request/', views.add_address, name='add-address'),
    path('verify/', views.verify, name='verify'),
]

nightShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
app_name = 'store'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('products-by-category/<int:category_id>/<slug:slug>/', views.product_by_category, name='product_by_category'),
    path('product-detail/<int:product_id>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('add-to-favorite/<int:id>/', views.add_to_favorite, name='add_to-favorite'),
    path('list-favorites/', views.list_favorite, name='list_favorite'),
    path('remove-favorite/<int:id>/', views.remove_favorite, name='remove_favorite'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('add-email/', views.emails, name='add_email'),
    path('discount-code/', views.apply_copen, name='discount_code'),
]

account/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models
from django.contrib.auth.models import PermissionsMixin

# Create your models here.


class NightManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('شماره تلفتی وجود ندارد!')
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('سوپر یوزر باید is_staff مثبت باشد.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('سوپر یوزر باید is_superuser مثبت باشد.')

        return self.create_user(email, password, **extra_fields)


class NightUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=25, null=True, blank=True)
    last_name = models.CharField(max_length=25, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = NightManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

account/forms.py
from django import forms
from .models import NightUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm


class UserCreateForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'رمزعبور خود را وارد کنید'}),
        min_length=8,
        help_text='رمز عبور باید حداقل 8 رفم باشد.',
    )

    class Meta:
        model = NightUser
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={
                'id': 'username',
                'placeholder': 'ایمیل خود را وارد کنید'
            })
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if NightUser.objects.filter(email=email).exists():
            raise forms.ValidationError('این ایمیل از قبل وجود دارد.')
        return email


class VerifyEmail(forms.Form):
    token = forms.CharField(max_length=6, widget=forms.TextInput(attrs={'id': 'email', 'placeholder': 'کد تایید را '
                                                                                                      'وارد کنید'}))


class NightUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = NightUser
        fields = '__all__'
        # widgets = {}

    def clean_email(self):
        email = self.cleaned_data['email']
        if self.instance.pk:
            if NightUser.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('email already exists!')
        else:
            if NightUser.objects.filter(email=email).exists():
                raise forms.ValidationError('email already exists!')

        return email


class NightUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = NightUser
        fields = '__all__'

    def clean_email(self):
        email = self.cleaned_data['email']
        if self.instance.pk:
            if NightUser.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('این ایمیل قبلاً ثبت شده است!')
        else:
            if NightUser.objects.filter(email=email).exists():
                raise forms.ValidationError('این ایمیل قبلاً ثبت شده است!')
        return email


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ایمیل'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'رمز عبور'}))


class NewEmailForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = NightUser
        fields = ['email']

    def clean_email(self):
        email = self.cleaned_data['email']

        if self.instance.pk:
            if NightUser.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('این ایمیل قبلاً ثبت شده است!')
        else:
            if NightUser.objects.filter(email=email).exists():
                raise forms.ValidationError('این ایمیل قبلاً ثبت شده است!')
        return email


class DetailAccountForm(forms.ModelForm):
    class Meta:
        model = NightUser
        fields = [
            'first_name',
            'last_name',
            'email'
        ]

    first_name = forms.CharField(
        widget=forms.Textarea(attrs={

            'class': 'form-control mb-4',
            'type': 'text'
        }),
        label="نام"
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',

        }),
        label="نام خانوادگی"
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control text-left',
            'placeholder': 'ایمیل'
        }),
        label="آدرس ایمیل"
    )


class ForgetForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ایمیل'}))


class ConfirmCodeForgetPasswordForm(forms.Form):
    token = forms.CharField(label="کد تأیید", max_length=6, widget=forms.TextInput(attrs={
        'class': 'form-control text-left ltr',
        'placeholder': 'کد تأیید را وارد کنید'
    }))
    new_password = forms.CharField(label="رمز عبور جدید", widget=forms.PasswordInput(attrs={
        'class': 'form-control text-left ltr',
        'placeholder': 'رمز عبور جدید'
    }))
    confirm_password = forms.CharField(label="تکرار رمز عبور جدید", widget=forms.PasswordInput(attrs={
        'class': 'form-control text-left ltr',
        'placeholder': 'تکرار رمز عبور جدید'
    }))

account/views.py
import random
import time
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import UserCreateForm, VerifyEmail, LoginForm, DetailAccountForm, ForgetForm, ConfirmCodeForgetPasswordForm
from .models import NightUser
from django.contrib import messages
from django.core.cache import cache
from method import sendMail
from django.contrib.auth import login, authenticate, logout
from cart.models import Order
from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend


# Create your views here.


class EmailBackend(ModelBackend):
    def authenticate(self, request, email=None, password=None, **kwargs):
        try:
            user = get_user_model().objects.get(email=email)
            if user.check_password(password):
                return user
        except get_user_model().DoesNotExist:
            return None


def register_user(request):
    if request.method == 'POST':

        form = UserCreateForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']

            if NightUser.objects.filter(email=email).exists():
                messages.error(request, 'شما قبلا ثبت نام کردید وارد شوید')
                return redirect('login')  # +++

            else:

                token = ''.join(random.choices('1234567890abcdefghijklmnopqrstuvwxyz', k=6))
                cache.set(email, token, timeout=300)
                sendMail(email, token)
                request.session['email'] = email
                password = form.cleaned_data['password']
                request.session['password'] = password
                messages.success(request, 'ایمیل خود را برسی کنید')
                print(token)  # check

                return redirect('account:verify_token')
    else:

        form = UserCreateForm()

    return render(request, 'forms/register.html', {'form': form})


def verify_email(request):
    if request.method == 'POST':
        form = VerifyEmail(request.POST)
        if form.is_valid():
            email = request.session.get('email')
            token = form.cleaned_data['token']
            cache_token = cache.get(email)

            if cache_token == token:
                password = request.session['password']
                user = NightUser.objects.create(email=email)
                user.set_password(password)
                user.save()
                login(request, user)
                messages.success(request, 'ثبت نام با موفقیت انجام شد')
                return redirect('store:index')
            else:
                messages.error(request, 'کد تایید اشتباه است')
    else:
        form = VerifyEmail()
    return render(request, 'forms/verify_token.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, 'شما وارد شدید')
                return redirect('store:index')
            else:
                messages.error(request, 'رمز عبور یا ایمیل اشتباه است')
        else:
            messages.error(request, 'اطلاعات وارد شده نامعتبر است')
    else:
        form = LoginForm()
    return render(request, 'forms/login.html', {'form': form})


def log_out(request):
    logout(request)
    return redirect("store:index")


@login_required
def detail(request):
    user = request.user
    orders = Order.objects.filter(buyer=user)

    return render(request, 'account/detail.html', {'orders': orders, 'user': user})


def complete_detail_account(request):
    if request.method == 'POST':
        form = DetailAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'اطلاعات با موفقیت تغییر یافت')
        else:
            messages.error(request, 'خطا در بروزرسانی اطلاعات')
    else:
        initial = {'first_name': request.user.first_name, 'last_name': request.user.last_name,
                   'email': request.user.email}
        form = DetailAccountForm(initial, instance=request.user)

    return render(request, 'account/detail.html', {'form': form})


def forget_password(request):
    if request.method == 'POST':
        form = ForgetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            if not NightUser.objects.filter(email=email).exists():
                messages.error(request, 'همیچین ایمیلی وجود ندارد')
            else:
                token = ''.join(random.choices('1234567890abcdefghijklmnopqrstuvwxy', k=6))
                cache.set(email, token, timeout=301)
                sendMail(email, token)
                request.session['email'] = email
                messages.success(request, 'ایمیل خود را برسی کنید')
                print(token)  # check
                return redirect('account:confirm-password-change')

        else:
            messages.error(request, 'فرم مشکل دارد!')
    else:
        form = ForgetForm()

    return render(request, 'account/detail.html', {'form': form})


def verifi_token_forget_password(request):
    email = request.session.get('email')
    if not email:
        messages.error(request, 'درخواست نامعتبر است.')
    if request.method == 'POST':
        form = ConfirmCodeForgetPasswordForm(request.POST)
        if form.is_valid():
            token = form.cleaned_data['token']
            newpassword = form.cleaned_data['new_password']
            confirm = form.cleaned_data['confirm_password']

            if newpassword != confirm:
                messages.error(request, 'رمز عبورها باهم مطابقت ندارد.')
            elif cache.get(email) != token:
                messages.error(request, 'کد نادرست است یا منقضی شده است')
            else:
                user = NightUser.objects.get(email=email)
                user.set_password(confirm)
                user.save()
                cache.delete(email)
                del request.session['email']
                user = authenticate(request, email=email, password=confirm)
                if user:
                    login(request, user)
                    messages.success(request, 'رمز عبور با موفقیت تغییر کرد')
                    return redirect('store:index')
                else:
                    messages.error(request, 'مشکلی در ورود!')
    else:
        form = ConfirmCodeForgetPasswordForm()
    return render(request, 'account/confirm.html', {'form': form})


def forget_master_password(request):
    if request.method == 'POST':
        form = ForgetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            if not NightUser.objects.filter(email=email).exists():
                messages.error(request, 'همیچین ایمیلی وجود ندارد')
            else:
                token = ''.join(random.choices('1234567890abcdefghijklmnopqrstuvwxy', k=6))
                cache.set(email, token, timeout=301)
                sendMail(email, token)
                request.session['email'] = email
                messages.success(request, 'ایمیل خود را برسی کنید')
                print(token)  # check
                return redirect('account:confirm-password-change')

        else:
            messages.error(request, 'فرم مشکل دارد!')
    else:
        form = ForgetForm()

    return render(request, 'forms/forget_pass.html', {'form': form})

account/templates/partials/header.html
{% load static %}
    <div class="page-wrapper">
        <h1 class="d-none">قالب ریود، دمو شماره یک</h1>
    </div>
<!-- End Header -->
<header class="header rtl text-right">
    <div class="header-top ">
        <div class="container">
            <div class="header-right">
                <p class="welcome-msg">به فروشگاه الــماس شــب خوش آمـدید.</p>
            </div>
            <div class="header-left ">

                <span class="divider"></span>
                <a href="{% url 'store:contact_us' %}" class="contact d-lg-show"><i class="d-icon-map"></i>تماس با ما</a>
                {% if user.is_authenticated  %}
                    <a href="{% url 'account:logout' %}" class="link-to-tab">خروج</a>
                    <a href="{% url 'account:detail' %}" class="link-to-tab"><i class="d-icon-user"></i>{{ user.email }}</a>
                    {% else %}
                    <a href="{% url 'account:login' %}" class="link-to-tab"><i class="d-icon-user"></i>ورود</a>
                    <a href="{% url 'account:register' %}" class="link-to-tab"><i class="d-icon-user"></i>ثبت نام</a>
                {% endif %}

        </div>
    </div>
    </div>

    <!-- End HeaderTop -->
    <div class="header-middle sticky-header fix-top sticky-content  ">
        <div class="container">
            <div class="header-right">
                <a href="#" class="mobile-menu-toggle">
                    <i class="d-icon-bars2"></i>
                </a>
                <a href="{% url 'store:index' %}" class="logo">
                    <img src="{% static 'images/logo.png' %}" alt="logo" width="153" height="44" />
                </a>
                <!-- End Logo -->
                <div class="header-search hs-simple">
                    <form action="{% url 'store:search' %}" class="input-wrapper" method="get">
                        <input type="text" class="form-control" name="query" autocomplete="off"
                               placeholder="جستجو ..." required />
                        <button class="btn btn-search" type="submit" title="submit-button">
                            <i class="d-icon-search"></i>
                        </button>
                    </form>
                </div>
                <!-- End Header Search -->
            </div>
<div class="header-left ">
    <a href="tel:#" class="icon-box icon-box-side">
        <div class="icon-box-icon ml-0 ml-lg-2">
            <i class="d-icon-phone"></i>
        </div>
        <div class="icon-box-content d-lg-show">
            <h4 class="icon-box-title">پشتیبانی سایت:</h4>
            <p>09112345678</p>
        </div>
    </a>
    <span class="divider"></span>
<div class="wishlist">
    <a href="{% url 'store:list_favorite' %}" class="wishlist-toggle">
        <i class="d-icon-heart" style="position: relative;">
            <span class="cart-count my-wishlist-heart" style="position: absolute; top: -10px; right: -10px; background-color: red; color: white; border-radius: 50%; padding: 5px; min-width: 20px; text-align: center; font-size: 12px;">{{ number_favorite }}</span>
        </i>
    </a>


        <div class="canvas-overlay"></div>
        <div class="dropdown-box scrollable">
            <div class="canvas-header">
                <h4 class="canvas-title">علاقمندی</h4>
                <a href="{% url 'store:list_favorite' %}" class="btn btn-dark btn-link btn-icon-right  btn-close">بستن<i
                        class="d-icon-arrow-left"></i><span class="sr-only">محصولات مورد علاقه</span></a>
            </div>
            <div class="products scrollable">
                <!-- در اینجا محصولات علاقه‌مندی‌ها را باید نمایش دهید -->
            </div>
            <a href="{% url 'store:list_favorite' %}" class="btn btn-dark wishlist-btn mt-4">
                <span>نمایش لیست</span></a>
        </div>
    </div>
    <span class="divider"></span>
    <div class="dropdown cart-dropdown type2 off-canvas mr-0 mr-lg-2">
        <a href="#" class="cart-toggle label-block link">
            <div class="cart-label d-lg-show">
                <span class="cart-name">سبد خرید:</span>
                <span class="cart-price my-price">{{ cart.get_total_price }}تومـان</span>
            </div>
            <i class="d-icon-bag"><span class="cart-count my-item-count">{{ cart|length }}</span></i>
        </a>
        <div class="canvas-overlay"></div>
        <div class="dropdown-box">
            <div class="canvas-header">
                <h4 class="canvas-title">سبد خرید</h4>
                <a href="#" class="btn btn-dark btn-link btn-icon-right  btn-close">بستن<i
                        class="d-icon-arrow-left"></i><span class="sr-only">سبد خرید</span></a>
            </div>
            <div class="products scrollable reload">
                {% for item in cart %}
                <div class="product product-cart">
                    <figure class="product-media">
                        <a href="{% url 'store:product_detail' item.product.id item.product.slug %}">
                            <img src="{{ item.product.images.first.file.url }}" alt="product" width="80" height="88" />
                        </a>
                        <button class="btn btn-link btn-close remove_item" data-product-id="{{ item.product.id }}">
                            <i class="fas fa-times"></i><span class="sr-only">بستن</span>
                        </button>
                    </figure>
                    <div class="product-detail">
                        <a href="{% url 'store:product_detail' item.product.id item.product.slug %}" class="product-name">
                            {{ item.product.name }}
                        </a>
                        <div class="price-box">
                            <span class="product-price">{{ item.product.price }} تومان</span>
                        </div>
                        <div class="quantity-box">
                            <span>تعداد: {{ item.quantity }}</span>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p>سبد خرید شما خالی است</p>
                {% endfor %}
            </div>
            <div class="cart-total">
                <label>جمع سبد:</label>
                <span class="price price-total-1" >{{ cart.get_total_price }} تومان</span> <!-- مجموع قیمت -->
            </div>
            <div class="cart-action">
                <a href="{% url 'cart:cart-detail' %}" class="btn btn-dark btn-link">سبد خرید</a>
                <a href="{% url 'cart:add-address' %}" class="btn btn-dark"><span>پرداخت</span></a>
            </div>
        </div>
    </div>
</div>

        </div>
    </div>
    <div class="header-bottom d-lg-show ">
        <div class="container">
            <div class="header-right">
                <nav class="main-nav">
                    <ul class="menu">
                        <li class="active">
                            <a href="{% url 'store:index' %}">صفحه نخست</a>
                        </li>
                        <li class="submenu submenu-container">
                            <a href="{% url 'store:index' %}">دسته بندی </a>
                            <div class="megamenu">
                                <div class="row">
                                    <div class="col-6 col-sm-4 col-md-4 col-lg-3">
                                        <h4 class="menu-title">دسته بندی ها</h4>
<ul>
    <li><a href="{% url 'store:product_by_category' category_id=10 slug='artistic' %}">هنری ها</a></li>
    <li><a href="{% url 'store:product_by_category' category_id=6 slug='household-items' %}">مصارف خانگی</a></li>
    <li><a href="{% url 'store:product_by_category' category_id=1 slug='household-items' %}">طروف تزئینی</a></li>
    <li><a href="{% url 'store:product_by_category' category_id=1 slug='None' %}">همه ی محصولات</a></li>
</ul>

                                    </div>
                                    <div class="col-6 col-sm-4 col-md-4 col-lg-3">
                                        <h4 class="menu-title">-</h4>
                                        <ul>
                                            <li><a href="{% url 'store:index' %}">-</a></li>
                                            <li><a href="{% url 'store:index' %}">-</a></li>
                                            <li><a href="{% url 'store:index' %}">-</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-6 col-sm-4 col-md-4 col-lg-3">
                                        <h4 class="menu-title">-</h4>
                                        <ul>
                                            <li><a href="{% url 'store:index' %}">-</a></li>
                                            <li><a href="{% url 'store:index' %}">- </a></li>
                                            <li><a href="{% url 'store:index' %}"> - </a></li>

                                        </ul>
                                    </div>
                                    <div class="col-6 col-sm-4 col-md-4 col-lg-3 menu-banner menu-banner1 banner banner-fixed">
                                        <figure>
                                            <img src="{% static 'images/category.jpg' %}" alt="Menu banner" width="221"
                                                 height="330" />
                                        </figure>
{#                                        <div class="banner-content y-50 text-right rtl">#}
{#                                            <h4 class="banner-subtitle font-weight-bold text-primary ls-m">#}
{#                                                فروش#}
{#                                            </h4>#}
{#                                            <h3 class="banner-title font-weight-bold">#}
{#                                                <span class="">بالای</span>%70 تخفیف#}
{#                                            </h3>#}
{#                                            <a href="shop.html" class="btn btn-link btn-underline">#}
{#                                                مشاهده و انتخاب <i class="d-icon-arrow-left"></i>#}
{#                                            </a>#}
{#                                        </div>#}
                                    </div>
                                    <!-- End Megamenu -->
                                </div>
                            </div>
                        </li>
                        <li class="submenu submenu-container">
                            <a href="{% url 'store:index' %}">محصولات</a>
                            <div class="megamenu">
                                <div class="row">
                                    <div class="col-6 col-sm-4 col-md-3">
                                        <h4 class="menu-title">جدیدترین محصولات</h4>
                                        <ul>
                                            {% for product in new_product|slice:"0:10" %}
                                            <li><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-6 col-sm-4 col-md-3">
                                        <h4 class="menu-title">پر فروش ترین محصولات</h4>
                                        <ul>
                                            {% for product in top_sell|slice:"10:20" %}
                                            <li><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-6 col-sm-4 col-md-3">
                                        <h4 class="menu-title">همه ی محصولات</h4>
                                        <ul>
                                            {% for product in productss|slice:"20:" %}
                                            <li><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-6 col-sm-4 col-md-3 menu-banner menu-banner2 banner banner-fixed">
                                        <figure>
                                            <img src="{% static 'images/myshop-ai.jpg' %}" alt="Menu banner" width="221"
                                                 height="330" />
                                        </figure>
                                    </div>
                                    <!-- End MegaMenu -->
                                </div>
                            </div>
                        </li>
                        <li class="">
                            <a href="#">صفحات</a>
                            <ul>
                                <li><a href="{% url 'store:about_us' %}">درباره ما</a></li>
                                <li><a href="{% url 'account:detail' %}">حساب کاربری</a></li>
                                <li><a href="{% url 'store:list_favorite' %}">علاقه مندی</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'store:about_us' %}">درباره ما</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>