blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('blog/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('blog-comments/<int:blog_id>/', views.add_comment, name='add_comment'),
]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add-to-cart'),
    path('cart-status/', views.cart_status, name='cart-status'),
    path('remove-item/', views.remove_item, name='remove-item'),
    path('detail/', views.cart_detail, name='cart-detail'),
    path('update-cart/', views.update_quantity, name='update-quantity'),
    path('order/<int:order_id>/', views.order, name='order'),
    path('request/', views.add_address, name='add-address'),
    path('verify/', views.verify, name='verify'),
]

nightShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
app_name = 'store'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('products-by-category/<int:category_id>/<slug:slug>/', views.product_by_category, name='product_by_category'),
    path('product-detail/<int:product_id>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('add-to-favorite/<int:id>/', views.add_to_favorite, name='add_to-favorite'),
    path('list-favorites/', views.list_favorite, name='list_favorite'),
    path('remove-favorite/<int:id>/', views.remove_favorite, name='remove_favorite'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('add-email/', views.emails, name='add_email'),
    path('discount-code/', views.apply_copen, name='discount_code'),
]

store/forms.py
from  django import forms
from .models import Review, ContactUs, Emails


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment']


class SearchForm(forms.Form):
    query = forms.CharField(max_length=25)


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['content', 'name', 'email']


class EmailForm(forms.ModelForm):
    class Meta:
        model = Emails
        fields = ['email']

store/views.py
from datetime import timedelta
from django.http import JsonResponse
from .forms import ReviewForm
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.timezone import now
from django.views.generic import ListView
from .models import Product, Category, ProductFeatureName, Review, FavoriteProduct, Copen, UserCopenUsage, Banner
from django.contrib.auth.decorators import login_required
from blog.models import BlogPost
from .forms import SearchForm, ContactUsForm, EmailForm
from django.db.models import Q
from cart.cart import Cart
from .models import SliderProduct


# Create your views here.


class Index(ListView):
    model = Product
    template_name = 'store/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        products = super().get_queryset()
        for product in products:
            if product.discount > 0:
                product.discounted_price = product.price - (product.price * product.discount // 100)
            else:
                product.discounted_price = product.price
        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['newest_product'] = Product.objects.order_by('-created')[:3]
        context['top'] = Product.objects.order_by('-sell')[:3]
        context['price'] = Product.objects.order_by('-price')[:3]
        context['off'] = Product.objects.order_by('-discount')[:3]
        context['blogs'] = BlogPost.objects.filter(status='published')
        context['categories'] = Category.objects.filter(parent__isnull=True)
        context['top_banners'] = Banner.objects.filter(status=True, position='top')
        context['middle_banners'] = Banner.objects.filter(status=True, position='middle')
        context['button_banners'] = Banner.objects.filter(status=True, position='button')
        cart = Cart(request=self.request)
        context['my_price'] = cart.get_total_price()
        context['top_slider_products'] = SliderProduct.objects.filter(status=True, location='top', product__isnull=False).distinct()
        context['middle_slider_products'] = SliderProduct.objects.filter(status=True, location='middle', product__isnull=False).distinct()
        context['button_slider_products'] = SliderProduct.objects.filter(status=True, location='button', product__isnull=False).distinct()
        return context


def product_by_category(request, category_id, slug):
    if slug == 'None':

        products = Product.objects.all()
        category = None

    else:

        category = get_object_or_404(Category, slug=slug, id=category_id)
        products = Product.objects.filter(category=category)

    # region filters

    # endregion
    categories = Category.objects.filter(parent__isnull=True)
    paginator = Paginator(products, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    all_features = ProductFeatureName.objects.values_list('name', flat=True)

    context = {
        'products': products,
        'category': category,
        'categories': categories,
        'page_obj': page_obj,
        'all_features': all_features
    }

    return render(request, 'store/by_category.html', context)


def product_detail(request, product_id, product_slug):
    product = get_object_or_404(Product, id=product_id, slug=product_slug)
    reviews = Review.objects.filter(product=product)
    parent_category = product.category.parent

    if parent_category:
        related_products = Product.objects.filter(category__parent=parent_category).exclude(id=product.id)[0:4]
    else:
        related_products = Product.objects.filter(category__parent=None).exclude(id=product.id)[0:4]
    if request.method == 'POST':

        form = ReviewForm(request.POST)

        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.product = product
            review.save()
            return redirect("store:product_detail", product_id=product.id, product_slug=product.slug)
    else:

        form = ReviewForm()

    context = {
        'product': product,
        'reviews': reviews,
        'form': form,
        'related_products': related_products
    }

    return render(request, 'store/detail.html', context)


def search(request):
    products = None
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            products = Product.objects.filter(
                Q(name__icontains=query) | Q(description__icontains=query)
            )
            print('_' * 100)
            print(products)
            print('_' * 100)

    return render(request, 'store/search.html', {'products': products})


@login_required
def add_to_favorite(request, id):
    saved = None
    product = Product.objects.get(id=id)

    if not product:
        return JsonResponse({'error': 'محصول پیدا نشد'})

    favorite = FavoriteProduct.objects.filter(user=request.user, product=product).first()
    if favorite:
        saved = False
        favorite.delete()
    else:
        FavoriteProduct.objects.create(user=request.user, product=product)

    favorite_count = FavoriteProduct.objects.filter(user=request.user).count()

    return JsonResponse({'success': True, 'saved': saved, 'favorite_count': favorite_count})


@login_required
def list_favorite(request):
    user = request.user
    products = FavoriteProduct.objects.filter(user=user)
    return render(request, 'store/list_favorite.html', {'products': products})


@login_required
def remove_favorite(request, id):
    if request.method == 'POST':
        favorite = get_object_or_404(FavoriteProduct, user=request.user, product_id=id)
        favorite.delete()
        favorite_count = FavoriteProduct.objects.filter(user=request.user).count()
        return JsonResponse({'success': True, 'message': 'محصول با موفقیت حذف شد', 'favorite_count': favorite_count})
    return JsonResponse({'success': False, 'error': 'درخواست نامعتبر یا کاربر احراز هویت نشده است'})


def about_us(request):
    return render(request, 'store/about_us.html')


def contact_us(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            form.save()
    else:
        form = ContactUsForm()
    return render(request, 'store/about_us.html', {'form': form})


def emails(request):
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('store:index')
    else:
        form = EmailForm()
    return render(request, 'partials/footer.html', {'form': form})


def apply_copen(request):
    if request.method == 'POST':
        copen_code = request.POST.get('copen_code')
        order_total = int(request.POST.get('order_total'))
        if not copen_code or not order_total:
            return JsonResponse({'success': False, 'message': 'کد منقضی شده است'})

        user = request.user
        try:
            copen = Copen.objects.get(code=copen_code, )
        except Copen.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'کد منقضی شده است'})

        if not copen:
            return JsonResponse({'success': False, 'message': 'کد منقضی شده است'})
        if copen.is_valid:
            discount = (order_total * copen.discount_percent) // 100
            total = order_total - discount

            UserCopenUsage.objects.create(
                user=user, copen=copen
            )

            return JsonResponse({
                'total32': total,
                'discount': discount,
                'success': True
            })
        else:
            return JsonResponse({'success': False, 'message': 'کد تخفیف نا معتبر است'})
    return JsonResponse({'success': False, 'message': 'کد نامعتبر است'})

store/templates/store/by_category.html
{% extends 'parent/base.html' %}
{% load static %}

{% block content %}
                <main class="main rtl text-right">
                <div class="page-header"
                     {% if category.id == 1 %}
                        style="background-image: url('{% static 'images/taziin.jpg' %}'); background-color: blue">
                     {% elif category.id == 10 %}
                         style="background-image: url('{% static 'images/honar.jpg' %}'); background-color: blue">
                     {% elif category.id == 6 %}
                         style="background-image: url('{% static 'images/hom.jpg' %}'); background-color: blue">
                     {% else %}
                         style="background-image: url('{% static 'images/hom.jpg' %}'); background-color: blue">
                     {% endif %}
                    <h1 class="page-title">فروشگاه</h1>
                    <ul class="breadcrumb">
                        <li><a href="{% url 'store:index' %}"><i class="d-icon-home"></i></a></li>
                        <li class="delimiter">/</li>
                        <li>فروشگاه</li>
                    </ul>
                </div>
                <!-- End PageHeader -->
                <div class="page-content mb-10 pb-3">
                    <div class="container ltr">
                        <div class="row main-content-wrap gutter-lg">
                            <aside
                                class="col-lg-3 right-sidebar sidebar-fixed sidebar-toggle-remain shop-sidebar sticky-sidebar-wrapper">
                                <div class="sidebar-overlay"></div>
                                <a class="sidebar-close" href="#"><i class="d-icon-times"></i></a>
                                <div class="sidebar-content">
                                    <div class="sticky-sidebar" data-sticky-options="{'top': 10}">
                                        <div class="filter-actions mb-4">
                                            <a href="#"
                                                class="sidebar-toggle-btn toggle-remain btn btn-outline btn-primary btn-icon-left btn-rounded">فیلتر<i
                                                    class="d-icon-arrow-left"></i></a>
                                        </div>
                                        <div class="widget widget-collapsible">
                                            <h3 class="widget-title">همه دسته بندی ها</h3>
                                            <ul class="widget-body filter-items search-ul">
                                                <li>
                                                    {% for cate in categories %}
                                                        <a href="{% url 'store:product_by_category' category_id=cate.id slug=cate.slug %}" {% if category and category.id == cate.id %}class="active"{% endif %}>
                                                            {{ cate.name }}
                                                        </a>
                                                    {% endfor %}
                                                </li>
                                            </ul>
                                        </div>



                                    </div>
                                </div>
                            </aside>
                            <div class="col-lg-9 main-content">
                                <nav class="toolbox sticky-toolbox sticky-content fix-top rtl">
                                    <div class="toolbox-right">
                                        <div class="toolbox-item toolbox-sort select-box text-dark">
                                            <label>مرتب شود با  :</label>
                                            <select name="orderby" class="form-control">
                                                <option value="default">پیش فرض</option>

                                            </select>
                                        </div>
                                    </div>
                                </nav>
                                <div class="row cols-2 cols-sm-3 product-wrapper">
                                    {% for product in page_obj %}
                                        <div class="product-wrap">
                                            <div class="product">
                                                <figure class="product-media">
                                                    <a href="{{ product.get_absolute_url }}">
                                                        <img src="{{ product.images.first.file.url }}" alt="product" width="280" height="315">
                                                    </a>
                                                    <div class="product-label-group">
                                                        {% if product.is_new %}
                                                            <label class="product-label label-new">جدید</label>
                                                        {% endif %}
                                                        <label class="product-label label-sale">{{ product.discount }}%</label>
                                                    </div>
                <div class="product-action-vertical">
                    <a href="" class="btn-product-icon btn-cart" title="افزودن به سبد خرید" data-product-id="{{ product.id }}"><i class="d-icon-bag" id="added"></i></a>
                    <a href="#" class="btn-product-icon btn-wishlist" title="اضافه به علاقه‌مندی" data-product-id="{{ product.id }}"><i class="d-icon-heart"></i></a>
                </div>
                                                    <div class="product-action">
                                                        <a href="{{ product.get_absolute_url }}" class="btn-product " title="مشاهده و انتخاب ">مشاهده و انتخاب
                                                            </a>
                                                    </div>
                                                </figure>
                                                <div class="product-details rtl">
                                                    <div class="product-cat">
                                                        <a href="{% url 'store:product_by_category' category_id=1 slug='decorative' %}">{{ product.category.name }}</a>
                                                    </div>
                                                    <h3 class="product-name">
                                                        <a href="product.html">{{ product.name }}</a>
                                                    </h3>
                                                    <div class="product-price">
                                                        <ins class="new-price"> {{ product.new_price }} تومان</ins><del class="old-price">{{ product.price}} تومان</del>
                                                    </div>
                                                    <div class="ratings-container">
                                                        <div class="ratings-full">
                                                            <span class="ratings" style="width:60%"></span>
                                                            <span class="tooltiptext tooltip-top"></span>
                                                        </div>
                                                        <span  class="rating-reviews">( {{ product.inventory }}  عدد در انبار )</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}


    <nav class="toolbox toolbox-pagination">
        <p class="show-info">نمایش
            <span>{{ page_obj.start_index }} محصول از</span> {{ page_obj.paginator.count }}
        </p>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link page-link-prev" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <i class="d-icon-arrow-right"></i>قبلی
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link page-link-prev" aria-disabled="true">
                        <i class="d-icon-arrow-right"></i>قبلی
                    </a>
                </li>
            {% endif %}

            {% for page_num in page_obj.paginator.page_range %}
                {% if page_num == page_obj.number %}
                    <li class="page-item active">
                        <a class="page-link">{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link page-link-next" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        بعدی<i class="d-icon-arrow-left"></i>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link page-link-next" aria-disabled="true">
                        بعدی<i class="d-icon-arrow-left"></i>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        // اضافه کردن به سبد خرید
        $('.btn-cart').click(function (e) {
            e.preventDefault();
            var button = $(this);
            var productId = button.data('product-id');

            $.ajax({
                type: 'POST',
                url: '{% url "cart:add-to-cart" 0 %}'.replace('0', productId),
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (data) {
                    // به‌روزرسانی سبد خرید
                    $('.reload').load(location.href + " .reload");
                    $('.price-total-1').text(data.total_price);
                    $('.my-price').text(data.total_price);
                    $('.my-item-count').text(data.item_count);
                },
                error: function (xhr) {
                    var response = JSON.parse(xhr.responseText);
                    console.log(response.error || "خطایی رخ داده است.");
                }
            });
        });

        // حذف از سبد خرید
        $(document).on('click', '.remove_item', function (e) {
            e.preventDefault();
            var button = $(this);
            var productId = button.data('product-id');

            $.ajax({
                type: 'POST',
                url: '{% url "cart:remove-item" %}',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'item_id': productId
                },
                success: function (data) {
                    if (data.success) {
                        button.closest('.product').remove();
                        $('.price-total-1').text(data.total_price);
                        $('.my-price').text(data.total_price);
                        $('.my-item-count').text(data.item_count);


                        if (data.item_count === 0) {
                            $('.reload').html('<p>سبد خرید شما خالی است</p>');
                        }
                    } else {
                        console.log(data.error || "خطایی رخ داده است.");
                    }
                },
                error: function (xhr) {
                    console.log("خطایی رخ داده است.");
                }
            });
        });
        $('.btn-wishlist').click(function () {
        var button = $(this);
        var product_id = button.data('product-id')

            $.ajax({
               url: '{% url 'store:add_to-favorite' 0 %}'.replace('0', product_id),
                data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function (data) {
                   console.log('success');
                   $('.my-wishlist-heart').text(data.favorite_count)
                },
                error: function (error) {
                   console.log(error)
                },
            });
        });
    });
</script>
{% endblock %}

store/templates/store/search.html
{% extends 'parent/base.html' %}
{% load static %}
{% block content %}



<div class="code-template">
                            <div class="row product-wrapper">

                                {% for item in products %}
                                <div class="col-md-3 col-6">
                                    <div class="product text-center">
                                        <figure class="product-media">
                                            <a href="{{ item.get_absolute_url }}">
                                                <img src="{{ item.images.first.file.url }}" alt="product" width="280" height="315">
                                            </a>
                                            <div class="product-action-vertical">
                                                <a href="#" class="btn-product-icon btn-cart" data-toggle="modal" data-target="#addCartModal" title="اضافه به خرید" data-product-id="{{ item.id }}"><i class="d-icon-bag"></i></a>
                                                <a href="#" class="btn-product-icon btn-wishlist" title="اضافه به علاقه مندی" data-product-id="{{ item.id }}"><i class="d-icon-heart"></i></a>
                                            </div>
                                            <div class="product-action">
                                                <a href="{{ item.get_absolute_url }}" class="btn-product" title="مشاهده و انتخاب ">مشاهده و انتخاب
                                                    </a>
                                            </div>
                                        </figure>
                                        <div class="product-details rtl">
                                            <div class="product-cat">
                                                <a href="{% url 'store:product_by_category' item.category.id item.category.slug %}">{{ item.category.name }}</a>
                                            </div>
                                            <h3 class="product-name">
                                                <a href="{{ item.get_absolute_url }}">{{ item.name }}</a>
                                            </h3>
                                            <div class="product-price">
                                                <span class="price"> {{ item.new_price }} تومان </span>
                                            </div>
                                            <div class="ratings-container">

                                                <a href="{{ item.get_absolute_url }}" class="rating-reviews">( از {{ item.sell }}خرید )</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                    {% empty %}
                                    <h2 class="title title-center mb-5">چیزی پیدا نشد!</h2>
                                {% endfor %}
                            </div>
                        </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        // اضافه کردن به سبد خرید
        $('.btn-cart').click(function (e) {
            e.preventDefault();
            var button = $(this);
            var productId = button.data('product-id');

            $.ajax({
                type: 'POST',
                url: '{% url "cart:add-to-cart" 0 %}'.replace('0', productId),
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (data) {
                    // به‌روزرسانی سبد خرید
                    $('.reload').load(location.href + " .reload");
                    $('.price-total-1').text(data.total_price);
                    $('.my-price').text(data.total_price);
                    $('.my-item-count').text(data.item_count);
                },
                error: function (xhr) {
                    var response = JSON.parse(xhr.responseText);
                    console.log(response.error || "خطایی رخ داده است.");
                }
            });
        });

        // حذف از سبد خرید
        $(document).on('click', '.remove_item', function (e) {
            e.preventDefault();
            var button = $(this);
            var productId = button.data('product-id');

            $.ajax({
                type: 'POST',
                url: '{% url "cart:remove-item" %}',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'item_id': productId
                },
                success: function (data) {
                    if (data.success) {
                        button.closest('.product').remove();
                        $('.price-total-1').text(data.total_price);
                        $('.my-price').text(data.total_price);


                        if (data.item_count === 0) {
                            $('.reload').html('<p>سبد خرید شما خالی است</p>');
                        }
                    } else {
                        console.log(data.error || "خطایی رخ داده است.");
                    }
                },
                error: function (xhr) {
                    console.log("خطایی رخ داده است.");
                }
            });
        });
        $('.btn-wishlist').click(function () {
        var button = $(this);
        var product_id = button.data('product-id')

            $.ajax({
               url: '{% url 'store:add_to-favorite' 0 %}'.replace('0', product_id),
                data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function (data) {
                   console.log('success');
                    $('.favorite_count').text(data.favorite_count)
                },
                error: function (error) {
                   console.log(error)
                },
            });
        });
    });
</script>


{% endblock %}