account/urls.py
from django.urls import path, include
from . import views
app_name = 'account'

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('verify_token/', views.verify_email, name='verify_token'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('detail/', views.detail, name='detail'),
    path('complete-information/', views.complete_detail_account, name='complete-information'),
    path('forget-password/', views.forget_password, name='forget-password'),
    path('confirm-password-change/', views.verifi_token_forget_password, name='confirm-password-change'),
    path('forget-master-password/', views.forget_master_password, name='forget-master-master'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('blog/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('blog-comments/<int:blog_id>/', views.add_comment, name='add_comment'),
]

nightShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
app_name = 'store'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('products-by-category/<int:category_id>/<slug:slug>/', views.product_by_category, name='product_by_category'),
    path('product-detail/<int:product_id>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('add-to-favorite/<int:id>/', views.add_to_favorite, name='add_to-favorite'),
    path('list-favorites/', views.list_favorite, name='list_favorite'),
    path('remove-favorite/<int:id>/', views.remove_favorite, name='remove_favorite'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('add-email/', views.emails, name='add_email'),
    path('discount-code/', views.apply_copen, name='discount_code'),
]

account/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models
from django.contrib.auth.models import PermissionsMixin

# Create your models here.


class NightManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('شماره تلفتی وجود ندارد!')
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('سوپر یوزر باید is_staff مثبت باشد.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('سوپر یوزر باید is_superuser مثبت باشد.')

        return self.create_user(email, password, **extra_fields)


class NightUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=25, null=True, blank=True)
    last_name = models.CharField(max_length=25, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = NightManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

account/forms.py
from django import forms
from .models import NightUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm


class UserCreateForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'رمزعبور خود را وارد کنید'}),
        min_length=8,
        help_text='رمز عبور باید حداقل 8 رفم باشد.',
    )

    class Meta:
        model = NightUser
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={
                'id': 'username',
                'placeholder': 'ایمیل خود را وارد کنید'
            })
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if NightUser.objects.filter(email=email).exists():
            raise forms.ValidationError('این ایمیل از قبل وجود دارد.')
        return email


class VerifyEmail(forms.Form):
    token = forms.CharField(max_length=6, widget=forms.TextInput(attrs={'id': 'email', 'placeholder': 'کد تایید را '
                                                                                                      'وارد کنید'}))


class NightUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = NightUser
        fields = '__all__'
        # widgets = {}

    def clean_email(self):
        email = self.cleaned_data['email']
        if self.instance.pk:
            if NightUser.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('email already exists!')
        else:
            if NightUser.objects.filter(email=email).exists():
                raise forms.ValidationError('email already exists!')

        return email


class NightUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = NightUser
        fields = '__all__'

    def clean_email(self):
        email = self.cleaned_data['email']
        if self.instance.pk:
            if NightUser.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('این ایمیل قبلاً ثبت شده است!')
        else:
            if NightUser.objects.filter(email=email).exists():
                raise forms.ValidationError('این ایمیل قبلاً ثبت شده است!')
        return email


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ایمیل'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'رمز عبور'}))


class NewEmailForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = NightUser
        fields = ['email']

    def clean_email(self):
        email = self.cleaned_data['email']

        if self.instance.pk:
            if NightUser.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
                raise forms.ValidationError('این ایمیل قبلاً ثبت شده است!')
        else:
            if NightUser.objects.filter(email=email).exists():
                raise forms.ValidationError('این ایمیل قبلاً ثبت شده است!')
        return email


class DetailAccountForm(forms.ModelForm):
    class Meta:
        model = NightUser
        fields = [
            'first_name',
            'last_name',
            'email'
        ]

    first_name = forms.CharField(
        widget=forms.Textarea(attrs={

            'class': 'form-control mb-4',
            'type': 'text'
        }),
        label="نام"
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',

        }),
        label="نام خانوادگی"
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control text-left',
            'placeholder': 'ایمیل'
        }),
        label="آدرس ایمیل"
    )


class ForgetForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ایمیل'}))


class ConfirmCodeForgetPasswordForm(forms.Form):
    token = forms.CharField(label="کد تأیید", max_length=6, widget=forms.TextInput(attrs={
        'class': 'form-control text-left ltr',
        'placeholder': 'کد تأیید را وارد کنید'
    }))
    new_password = forms.CharField(label="رمز عبور جدید", widget=forms.PasswordInput(attrs={
        'class': 'form-control text-left ltr',
        'placeholder': 'رمز عبور جدید'
    }))
    confirm_password = forms.CharField(label="تکرار رمز عبور جدید", widget=forms.PasswordInput(attrs={
        'class': 'form-control text-left ltr',
        'placeholder': 'تکرار رمز عبور جدید'
    }))

account/views.py
import random
import time
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import UserCreateForm, VerifyEmail, LoginForm, DetailAccountForm, ForgetForm, ConfirmCodeForgetPasswordForm
from .models import NightUser
from django.contrib import messages
from django.core.cache import cache
from method import sendMail
from django.contrib.auth import login, authenticate, logout
from cart.models import Order
from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend


# Create your views here.


class EmailBackend(ModelBackend):
    def authenticate(self, request, email=None, password=None, **kwargs):
        try:
            user = get_user_model().objects.get(email=email)
            if user.check_password(password):
                return user
        except get_user_model().DoesNotExist:
            return None


def register_user(request):
    if request.method == 'POST':

        form = UserCreateForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']

            if NightUser.objects.filter(email=email).exists():
                messages.error(request, 'شما قبلا ثبت نام کردید وارد شوید')
                return redirect('login')  # +++

            else:

                token = ''.join(random.choices('1234567890abcdefghijklmnopqrstuvwxyz', k=6))
                cache.set(email, token, timeout=300)
                sendMail(email, token)
                request.session['email'] = email
                password = form.cleaned_data['password']
                request.session['password'] = password
                messages.success(request, 'ایمیل خود را برسی کنید')
                print(token)  # check

                return redirect('account:verify_token')
    else:

        form = UserCreateForm()

    return render(request, 'forms/register.html', {'form': form})


def verify_email(request):
    if request.method == 'POST':
        form = VerifyEmail(request.POST)
        if form.is_valid():
            email = request.session.get('email')
            token = form.cleaned_data['token']
            cache_token = cache.get(email)

            if cache_token == token:
                password = request.session['password']
                user = NightUser.objects.create(email=email)
                user.set_password(password)
                user.save()
                login(request, user)
                messages.success(request, 'ثبت نام با موفقیت انجام شد')
                return redirect('store:index')
            else:
                messages.error(request, 'کد تایید اشتباه است')
    else:
        form = VerifyEmail()
    return render(request, 'forms/verify_token.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, 'شما وارد شدید')
                return redirect('store:index')
            else:
                messages.error(request, 'رمز عبور یا ایمیل اشتباه است')
        else:
            messages.error(request, 'اطلاعات وارد شده نامعتبر است')
    else:
        form = LoginForm()
    return render(request, 'forms/login.html', {'form': form})


def log_out(request):
    logout(request)
    return redirect("store:index")


@login_required
def detail(request):
    user = request.user
    orders = Order.objects.filter(buyer=user)

    return render(request, 'account/detail.html', {'orders': orders, 'user': user})


def complete_detail_account(request):
    if request.method == 'POST':
        form = DetailAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'اطلاعات با موفقیت تغییر یافت')
        else:
            messages.error(request, 'خطا در بروزرسانی اطلاعات')
    else:
        initial = {'first_name': request.user.first_name, 'last_name': request.user.last_name,
                   'email': request.user.email}
        form = DetailAccountForm(initial, instance=request.user)

    return render(request, 'account/detail.html', {'form': form})


def forget_password(request):
    if request.method == 'POST':
        form = ForgetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            if not NightUser.objects.filter(email=email).exists():
                messages.error(request, 'همیچین ایمیلی وجود ندارد')
            else:
                token = ''.join(random.choices('1234567890abcdefghijklmnopqrstuvwxy', k=6))
                cache.set(email, token, timeout=301)
                sendMail(email, token)
                request.session['email'] = email
                messages.success(request, 'ایمیل خود را برسی کنید')
                print(token)  # check
                return redirect('account:confirm-password-change')

        else:
            messages.error(request, 'فرم مشکل دارد!')
    else:
        form = ForgetForm()

    return render(request, 'account/detail.html', {'form': form})


def verifi_token_forget_password(request):
    email = request.session.get('email')
    if not email:
        messages.error(request, 'درخواست نامعتبر است.')
    if request.method == 'POST':
        form = ConfirmCodeForgetPasswordForm(request.POST)
        if form.is_valid():
            token = form.cleaned_data['token']
            newpassword = form.cleaned_data['new_password']
            confirm = form.cleaned_data['confirm_password']

            if newpassword != confirm:
                messages.error(request, 'رمز عبورها باهم مطابقت ندارد.')
            elif cache.get(email) != token:
                messages.error(request, 'کد نادرست است یا منقضی شده است')
            else:
                user = NightUser.objects.get(email=email)
                user.set_password(confirm)
                user.save()
                cache.delete(email)
                del request.session['email']
                user = authenticate(request, email=email, password=confirm)
                if user:
                    login(request, user)
                    messages.success(request, 'رمز عبور با موفقیت تغییر کرد')
                    return redirect('store:index')
                else:
                    messages.error(request, 'مشکلی در ورود!')
    else:
        form = ConfirmCodeForgetPasswordForm()
    return render(request, 'account/confirm.html', {'form': form})


def forget_master_password(request):
    if request.method == 'POST':
        form = ForgetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            if not NightUser.objects.filter(email=email).exists():
                messages.error(request, 'همیچین ایمیلی وجود ندارد')
            else:
                token = ''.join(random.choices('1234567890abcdefghijklmnopqrstuvwxy', k=6))
                cache.set(email, token, timeout=301)
                sendMail(email, token)
                request.session['email'] = email
                messages.success(request, 'ایمیل خود را برسی کنید')
                print(token)  # check
                return redirect('account:confirm-password-change')

        else:
            messages.error(request, 'فرم مشکل دارد!')
    else:
        form = ForgetForm()

    return render(request, 'forms/forget_pass.html', {'form': form})

account/templates/forms/forget_pass.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %}forget password{% endblock %}

    {% block content %}

        <form method="post" action="{% url 'account:forget-password' %}">
        {% csrf_token %}
        <fieldset>
            <legend>فراموشی پسورد</legend>
            <label>ایمیل</label>
            <input type="email" class="form-control text-left ltr" name="email">

        </fieldset>
        <button type="submit" class="btn btn-primary">ارسال کد</button>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </form>

    {% endblock %}

account/templates/forms/login.html
<!-- login.html -->
{% extends 'parent/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/god.css' %}">{% endblock %}
{% block content %}
<main class="main rtl text-right">
    <nav class="breadcrumb-nav">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'store:index' %}"><i class="d-icon-home"></i></a></li>
                <li><a href="{% url 'store:index' %}">فروشگاه</a></li>
                <li>حساب کاربری</li>
            </ul>
        </div>
    </nav>
    <div class="page-content mt-6 pb-2 mb-10">
        <div class="container">
            <div class="login-popup">
                <div class="form-box">
                    <div class="tab tab-nav-simple tab-nav-boxed form-tab">
                        <ul class="nav nav-tabs nav-fill align-items-center border-no justify-content-center mb-5"
                            role="tablist">
                            <li class="nav-item">
                                <span class="nav-link active border-no lh-1 ls-normal" >ورود</span>
                            </li>

                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="signin">
                                <div class="login-field">
                                    <div class="login-background">

                                        <div class="login-form">
                                            <form method="post">
                                                {% csrf_token %}
                                                <div class="field username-field">
                                                    {{ form.email }}
                                                </div>
                                                <div class="field password-field">
                                                    {{ form.password }}
                                                </div>
                                                <div class="field button-field">
                                                    <button class="btn btn-dark btn-block btn-rounded" type="submit">ورود</button>
                                                </div>
                                                {% if messages %}
                                                    <ul class="messages">
                                                        {% for message in messages %}
                                                            <li class="{{ message.tags }}">{{ message }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %}


                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-choice text-center">
                                    <label class="ls-m"><a href="{% url 'account:register' %}">ایا حساب کاربری ندارید؟ثبت نام کنید</a></label>
                                    <label class="ls-m"><a href="{% url 'account:forget-master-master' %}">رمز عبور خود را فراموش کردید؟</a></label>
                                    <div class="social-links">
                                        <a href="#" class="social-link social-google fab fa-google border-no disabled"></a>
                                        <a href="#" class="social-link social-facebook fab fa-facebook-f border-no disabled"></a>
                                        <a href="#" class="social-link social-twitter fab fa-twitter border-no disabled"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

account/templates/forms/register.html
<!-- register.html -->
{% extends 'parent/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/god.css' %}">{% endblock %}
{% block content %}
<main class="main rtl text-right">
    <nav class="breadcrumb-nav">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'store:index' %}"><i class="d-icon-home"></i></a></li>
                <li><a href="{% url 'store:index' %}">فروشگاه</a></li>
                <li>حساب کاربری</li>
            </ul>
        </div>
    </nav>
    <div class="page-content mt-6 pb-2 mb-10">
        <div class="container">
            <div class="login-popup">
                <div class="form-box">
                    <div class="tab tab-nav-simple tab-nav-boxed form-tab">
                        <ul class="nav nav-tabs nav-fill align-items-center border-no justify-content-center mb-5"
                            role="tablist">

                            <li class="nav-item">
                                <a class="nav-link active border-no lh-1 ls-normal" href="#register">ثبت نام</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="register">
                                <div class="login-field">
                                    <div class="login-background">

                                        <div class="login-form">
                                            <form method="post">
                                                {% csrf_token %}
                                                <div class="field username-field form-control">
                                                    {{ form.email }}
                                                </div>
                                                <div class="field password-field form-control">
                                                    {{ form.password }}
                                                </div>
                                                <div class="field button-field">
                                                    <button class="btn btn-dark btn-block btn-rounded" type="submit">ثبت نام</button>
                                                </div>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-choice text-center">
                                    <label class="ls-m"><a href="{% url 'account:login' %}">حساب کاربری دارید؟وارد شوید</a></label>
                                    <div class="social-links">
                                        <a href="#" class="social-link social-google fab fa-google border-no disabled"></a>
                                        <a href="#" class="social-link social-facebook fab fa-facebook-f border-no disabled"></a>
                                        <a href="#" class="social-link social-twitter fab fa-twitter border-no disabled"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

account/templates/forms/verify_token.html
<!-- register.html -->
{% extends 'parent/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/god.css' %}">{% endblock %}
{% block content %}
<main class="main rtl text-right">
    <nav class="breadcrumb-nav">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'store:index' %}"><i class="d-icon-home"></i></a></li>
                <li><a href="{% url 'store:index' %}">فروشگاه</a></li>
                <li>حساب کاربری</li>
            </ul>
        </div>
    </nav>
    <div class="page-content mt-6 pb-2 mb-10">
        <div class="container">
            <div class="login-popup">
                <div class="form-box">
                    <div class="tab tab-nav-simple tab-nav-boxed form-tab">
                        <ul class="nav nav-tabs nav-fill align-items-center border-no justify-content-center mb-5"
                            role="tablist">

                            <li class="nav-item">
                                <a class="nav-link active border-no lh-1 ls-normal disabled" href="#register">تایید کد</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="register">
                                <div class="login-field">
                                    <div class="login-background">

                                        <div class="login-form">
                                            <form method="post">
                                                {% csrf_token %}
                                                <div class="field username-field form-control">
                                                    {{ form.token }}
                                                </div>

                                                <div class="field button-field">
                                                    <button class="btn btn-dark btn-block btn-rounded" type="submit">ثبت نام</button>
                                                </div>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-choice text-center">
                                    <label class="ls-m">یا ثبت نام با</label>
                                    <div class="social-links">
                                        <a href="#" class="social-link social-google fab fa-google border-no disabled"></a>
                                        <a href="#" class="social-link social-facebook fab fa-facebook-f border-no disabled"></a>
                                        <a href="#" class="social-link social-twitter fab fa-twitter border-no disabled"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}